### ISSUE TITLE
feat(docker): Dockerize ScholarSuite Application

### ISSUE THREAD

**Issue by AugustinMauroy** [AugustinMauroy/scholarsuite#41]
## Description

We need to dockerize the ScholarSuite application to facilitate deployment and ensure consistency between different environments. This includes creating Dockerfiles for the application and MySQL database, as well as configuring docker-compose.

## Tasks

1. Create a Dockerfile for the application.
2. Create a Dockerfile for MySQL.
3. Configure a `docker-compose.yml` file.
4. Update README.md with instructions for using Docker.
5. Test the docked application to make sure it works correctly.

## Acceptance Criteria

1. The application must be fully functional when run with Docker.
2. The database must be correctly initialized and accessible.
3. The `docker-compose.yml` file must be well documented and easy to use.
4. The README.md must be updated with clear instructions for running the application with Docker.

**Comment by vigneshwarap** [comment]
Hi @AugustinMauroy 
If you are ok, i would like to work on this issue.

**Comment by AugustinMauroy** [comment]
@vigneshwarap you are welcome to work on this issue

**Comment by AugustinMauroy** [comment]
Thanks @vigneshwarap for your help !
